language: android
android:
  components:
  - tools
  - tools
  - build-tools-23.0.3
  - android-24
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-22
  - sys-img-x86-android-17
jdk:
- oraclejdk8
env:
  global:
  - secure: koCWvGtI5Q89GUekJZBI7Usi+Ff/i2HgwwPUs+88U2un+iWJO6+lQLF8bj7sg2j3fK6rsrYnQUcM1CTY/R1xiCl4wnhO81QLmMMxMSA80giDZDBrDkbz+IfYFMPDI43tlsueunruXfdFOtIzvfTAjuK1bfxUPgGk+6zNm3QS6u8Fwdp1WUeRC/WAkY15i4/9uM1oMciKVieMlbCwboLvJLZiEsKuyYqednfWklwH55Dr17mFPIBGdtQYWDdhrilK27zh3MM9lC51c32OAPrh0t7j4pLGBHh9LEAFJuNn6XS7alDTccdQ2p+8kE5/IK/+lkpWXoI8+j3nhgFBLyBNX5v064NEFi6uy22zy90MLVjQmJ4SxBzfk1eDFYqgxX7Bhh94JAzE5MH+s+ohEXlm3JJ5CWTunyO0NMBdmuT7tj3vN8+TrsXFny1YbWEdYFcijl/IBd32G3AbRMC2Mavy8lLZxvuHBBKzAVtqR4wmg2gGQAiDGu0l757ZXdMVbO5SiN80Op3268NzJ9M6lHMtfitMXEp5b65B3HUPuVlyE+SJCTtbCI45st1UxNToeqduFV45GeMOKPmCmhxp/KNYNA4C9177hBRQ4+hS4jZgBnIvmJrwmKJ/pZIWIP1L02MexpT7twCU2dHd5/hPoz37Lg0v2JEcBFoLKsC31W71WUs=
  - secure: bEVVjFnUrfXNpCsx4+659FUU6s/R646QRuFiswL7D8g9r5O/dRJSfQdtmJB6Jw8NHmdI3+Y+y03lizb7oqjWWbJNoo3+26s+8UMsrgGi3u5tr33dtnYBEz52fk1nwVIL/FJOuemuLdRbQaHi9f2D5AVZxDdPaPD5GP4jvTHXzpEdieNetV1eeF/U7+hz4/ia2rmTz/NuZerZYrdHGUsRuHuHIk9uQ2FGlVB/g+4yxONm28AO0BnHHHdhqEtvYKtjMxl3Dxv+2/kWhQ3XXycBF3ECe9eEhdeRjtm6zA7y3WVWPkpiNVx07sP1YxvBErOmEwtu6azzcuGi939kN8kjKCnzuHkM1C2UYmqd+Z1g7ce9lGNDGU7fNVcNYUNCZcQrtog1jARiLj4CtljiR8aGounSEkMw1XGC5yqrKsTajCca1HEYJz9NZkMDaUCmDIZbrldsGhkphnXZJC+cG2wbIdhnR/+Wn6698zctqliHwqXZC3IjSyJHmBge1o4C1Ozh4ImjvC+5KZ+GBRdFvAABty0zROjFBBTOMPYBGglsdtCwcLgsGltfdoEZ0ClqOAn/tMu/N1BkR+4Tf++lttTgXQ77u0Mi9YNadghGTsPC83qkhH8VoyCIJf50DGQLEr7Q2u036PN8VL4dsnerhywanNcsJyiusB+pYPDUm8uo7Tc=
deploy:
  provider: bintray
  file: chartdescriptor.json
  user: whipsmith
  key:
    secure: hidPL8zX+BAa1ZfeEQpghc6Ihp0rhF3hhD7GnO/l8XuE2IrW6MgmLkVy8J0ftYWLDFPwOYs1AXHfJXlVdB3Kr9XmhMfJfEKFVqpVBSiRB8yDIF/ocdc4ICZ1APZwJAsno90mickS8eirWZN1Fh+o67sBrlY3yKI1XLlMOJ8A/zzHzFkI144t5VJbLSbbXBuf3dhc2Yl+gtH25xmt7cNlAf+ary0kczat7yaEdHvjMxAieegfZ0JGJk6XIC1DosOKKzTsAJk45cyvAFkcKT0b803bNHFgF5WBWsTkvCcJzHdKroZStiZrE99g5Ew3NgAB5mhNmMjavlM/7DCqRMf+CCGAgxrxFpI8jJ8uh/ExI9jFBD7SHGCQwGFllPTcjI3DkiJzAOCJv/TIIudHLbNBeffYHfMUlsPdv3Ifzg+6used3bOKQGOI/3PlTlLv3BeB7fuYXz0jzvwLJ3CsJ4HdF6D1f0a74QkGI9AC5rNvdpk0LypIMSNNCdbeuQGXn9/zI5v0fVcen2/GP/d67YOkn4joMEKFtPA/nc33Nrq6ExF/m7As9n/JwAX92aVtD/OHJi9SmSANKMklMLmeDkdNoFU22TJq9ORKLgEt+lemK0YO7peH8Mijboi4s617hqAJmJsS0qXN5BqzoW+z05WO7FPfNsTj10WCfZQ3E3uNnXk=
